#!/usr/bin/env python3
"""
Test script for PandaDock-ML integration

This script demonstrates the integration between PandaDock and PandaDock-ML,
showing how ML models can work with the existing physics-based infrastructure.
"""

import sys
import os
import numpy as np
from pathlib import Path

# Add the current directory to Python path
sys.path.insert(0, '.')

def test_basic_imports():
    """Test basic module imports"""
    print("=" * 60)
    print("TESTING BASIC IMPORTS")
    print("=" * 60)

    # Test core PandaDock imports
    try:
        from pandadock.docking.core import DockingEngine, DockingResult, Pose
        print("✓ Core PandaDock modules imported successfully")
    except ImportError as e:
        print(f"✗ Core PandaDock import failed: {e}")
        return False

    # Test ML CLI import
    try:
        from pandadock.ml_docking_cli import main, ML_AVAILABLE
        print(f"✓ ML CLI imported successfully (ML_AVAILABLE: {ML_AVAILABLE})")

        if ML_AVAILABLE:
            print("  → PyTorch is available - full ML functionality enabled")
        else:
            print("  → PyTorch not available - graceful fallback mode")

    except ImportError as e:
        print(f"✗ ML CLI import failed: {e}")
        return False

    return True

def test_cli_help_commands():
    """Test CLI help commands"""
    print("\n" + "=" * 60)
    print("TESTING CLI HELP COMMANDS")
    print("=" * 60)

    import subprocess

    # Test main PandaDock CLI
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pandadock.docking_cli', '--help'],
            env={**os.environ, 'PYTHONPATH': '.'},
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print("✓ Main PandaDock CLI help working")
        else:
            print(f"✗ Main PandaDock CLI help failed: {result.stderr}")
    except Exception as e:
        print(f"✗ Main PandaDock CLI test failed: {e}")

    # Test ML CLI
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pandadock.ml_docking_cli', '--help'],
            env={**os.environ, 'PYTHONPATH': '.'},
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print("✓ PandaDock-ML CLI help working")
        else:
            print(f"✗ PandaDock-ML CLI help failed: {result.stderr}")
    except Exception as e:
        print(f"✗ PandaDock-ML CLI test failed: {e}")

def test_pose_integration():
    """Test that ML and Physics systems can work with the same Pose objects"""
    print("\n" + "=" * 60)
    print("TESTING POSE OBJECT INTEGRATION")
    print("=" * 60)

    try:
        from pandadock.docking.core import Pose

        # Create a sample pose (as would be generated by either ML or physics)
        sample_coords = np.random.randn(20, 3)  # 20 atoms, 3D coordinates
        sample_center = np.mean(sample_coords, axis=0)

        pose = Pose(
            coordinates=sample_coords,
            center=sample_center,
            rotation=np.array([1.0, 0.0, 0.0, 0.0]),  # Identity quaternion
            conformer_id=0,
            energy=-5.2,
            confidence=0.85
        )

        print("✓ Created sample pose with basic properties")

        # Add ML-specific attributes (as would be done by ML models)
        pose.ml_confidence = 0.92
        pose.generation_method = 'diffusion'
        pose.ml_score = 0.78

        print("✓ Added ML-specific attributes to pose")

        # Add physics-specific attributes (as would be done by physics scoring)
        pose.physics_score = -6.1
        pose.energy_components = {
            'vdw': -3.2,
            'electrostatic': -2.1,
            'hbond': -0.8
        }

        print("✓ Added physics-specific attributes to pose")

        # Test pose serialization
        pose_dict = pose.to_dict()
        print("✓ Pose serialization working")

        # Verify all attributes are preserved
        expected_attrs = ['energy', 'confidence', 'coordinates', 'center']
        for attr in expected_attrs:
            if attr not in pose_dict:
                print(f"✗ Missing attribute in serialization: {attr}")
                return False

        print("✓ All core attributes preserved in serialization")
        print(f"  → Energy: {pose.energy:.2f} kcal/mol")
        print(f"  → Confidence: {pose.confidence:.3f}")
        print(f"  → ML Confidence: {pose.ml_confidence:.3f}")
        print(f"  → Generation Method: {pose.generation_method}")

        return True

    except Exception as e:
        print(f"✗ Pose integration test failed: {e}")
        return False

def test_docking_engine_compatibility():
    """Test that the DockingEngine can work with ML-enhanced workflows"""
    print("\n" + "=" * 60)
    print("TESTING DOCKING ENGINE COMPATIBILITY")
    print("=" * 60)

    try:
        from pandadock.docking.core import DockingEngine, DockingResult, Pose

        # Initialize the engine (same as used in regular PandaDock)
        engine = DockingEngine()

        # Try to register basic algorithms if available
        try:
            from pandadock.docking.algorithms.monte_carlo_cpu import MonteCarloDocker as MCDocker
            from pandadock.docking.scoring.physics_based import PhysicsBasedScoring

            engine.register_algorithm(MCDocker())
            engine.register_scoring_function('physics_based', PhysicsBasedScoring())
            print("✓ DockingEngine initialized with sample algorithms")
        except ImportError:
            print("✓ DockingEngine initialized (algorithms not available in test mode)")

        print("✓ DockingEngine basic functionality working")

        # Check that standard algorithms are available
        algorithms = engine.list_algorithms()
        if algorithms:
            print(f"✓ {len(algorithms)} standard algorithms available:")
            for alg in algorithms[:3]:  # Show first 3
                print(f"    - {alg}")
            if len(algorithms) > 3:
                print(f"    ... and {len(algorithms) - 3} more")
        else:
            print("⚠ No algorithms registered")

        # Check scoring functions
        scoring_functions = engine.list_scoring_functions()
        if scoring_functions:
            print(f"✓ {len(scoring_functions)} scoring functions available:")
            for sf in scoring_functions:
                print(f"    - {sf}")
        else:
            print("⚠ No scoring functions registered")

        # Create a mock result (as would be generated by hybrid pipeline)
        sample_poses = []
        for i in range(3):
            coords = np.random.randn(15, 3)
            pose = Pose(
                coordinates=coords,
                center=np.mean(coords, axis=0),
                rotation=np.array([1.0, 0.0, 0.0, 0.0]),
                conformer_id=i,
                energy=-4.5 - i * 0.5,  # Decreasing energy
                confidence=0.9 - i * 0.1
            )
            # Add hybrid attributes
            pose.ml_confidence = 0.8 + i * 0.05
            pose.physics_score = -5.0 - i * 0.3
            pose.generation_method = 'hybrid_ml_physics'
            sample_poses.append(pose)

        # Create a DockingResult (as would be done by hybrid pipeline)
        result = DockingResult(
            ligand_name="test_ligand",
            receptor_file="test_receptor.pdb",
            grid_center=np.array([0.0, 0.0, 0.0]),
            grid_dimensions=np.array([20.0, 20.0, 20.0]),
            algorithm_used="hybrid_ml_physics_diffusion",
            scoring_function="hybrid_ml_physics",
            poses=sample_poses
        )

        # Add ML-specific metadata
        result.ml_generation_time = 2.5
        result.physics_refinement_time = 8.3
        result.hybrid_scoring_time = 1.2

        print("✓ Created hybrid DockingResult with ML and physics components")

        # Test result methods
        best_pose = result.get_best_pose()
        if best_pose:
            print(f"✓ Best pose retrieval working (energy: {best_pose.energy:.2f})")

        top_poses = result.get_top_poses(2)
        if len(top_poses) == 2:
            print(f"✓ Top poses retrieval working ({len(top_poses)} poses)")

        return True

    except Exception as e:
        print(f"✗ DockingEngine compatibility test failed: {e}")
        return False

def test_ml_availability_detection():
    """Test ML availability detection and graceful fallback"""
    print("\n" + "=" * 60)
    print("TESTING ML AVAILABILITY DETECTION")
    print("=" * 60)

    try:
        from pandadock.ml_docking_cli import ML_AVAILABLE

        print(f"ML_AVAILABLE status: {ML_AVAILABLE}")

        if ML_AVAILABLE:
            print("✓ Full ML functionality is available")
            print("  → PyTorch is installed and working")
            print("  → All ML models should be functional")

            try:
                from pandadock.ml.feature_extraction import ProteinFeatureExtractor
                extractor = ProteinFeatureExtractor()
                print("  → Feature extraction modules working")
            except Exception as e:
                print(f"  ✗ Feature extraction test failed: {e}")

        else:
            print("✓ Graceful fallback mode is active")
            print("  → PyTorch is not available")
            print("  → ML commands will show helpful error messages")

            # Test that fallback classes provide helpful errors
            try:
                from pandadock.ml_docking_cli import DiffusionDockingModel
                model = DiffusionDockingModel()
                print("  ✗ Should have raised ImportError")
                return False
            except ImportError as e:
                if "PyTorch not available" in str(e):
                    print("  ✓ Fallback error message is helpful")
                else:
                    print(f"  ⚠ Unexpected error message: {e}")

        return True

    except Exception as e:
        print(f"✗ ML availability test failed: {e}")
        return False

def main():
    """Run all integration tests"""
    print("PandaDock-ML Integration Test Suite")
    print("Author: Pritam Kumar Panda @ Stanford University")
    print("Testing integration between PandaDock and PandaDock-ML")

    # Run all tests
    tests = [
        test_basic_imports,
        test_cli_help_commands,
        test_pose_integration,
        test_docking_engine_compatibility,
        test_ml_availability_detection
    ]

    passed = 0
    total = len(tests)

    for test in tests:
        try:
            if test():
                passed += 1
        except Exception as e:
            print(f"✗ Test {test.__name__} crashed: {e}")

    # Summary
    print("\n" + "=" * 60)
    print("INTEGRATION TEST SUMMARY")
    print("=" * 60)
    print(f"Tests passed: {passed}/{total}")

    if passed == total:
        print("🎉 ALL TESTS PASSED! PandaDock-ML is ready for use.")
        print("\nNext steps:")
        print("1. Install PyTorch for full ML functionality: pip install torch")
        print("2. Try the ML CLI: pandadock-ml --help")
        print("3. Run hybrid docking: pandadock-ml hybrid-dock --help")
    else:
        print(f"⚠ {total - passed} tests failed. Please check the output above.")

    return passed == total

if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)