"""
Default PandaDock docking algorithm.

`HierarchicalDocker` is the algorithm registered under the name ``pandadock`` and
used by ``pandadock dock``. It delegates to `PandaCoreDocker`, which performs a
Monte Carlo search with local optimization over translation, orientation and
ligand torsions, scored against precomputed affinity grids.

The previous implementation under this name performed a three-stage random
sampling procedure in which the majority of poses were generated by jittering the
input conformer around the box centre by roughly one Angstrom and ten degrees.
Because it also passed no ligand to the scoring function, every pose scored 0.0,
and poses were ranked by a proximity bonus rather than by any interaction energy.
It could not reproduce crystal poses and has been replaced rather than patched.
"""

from .pandacore import PandaCoreDocker


class HierarchicalDocker(PandaCoreDocker):
    """Flexible-ligand Monte Carlo docking, registered as ``pandadock``."""

    def __init__(self, name: str = "pandadock"):
        super().__init__(name)
